title: "Magical Musings"
theme: "jekyll-theme-leaf"
baseURL: "/magicalmusings.github.io/"

# for a clean URL
permalink: :slug

markdown: kramdown

social:
  twitter: anders_magi
  github: magicalmusings

plugins:
 - jekyll-feed
 - jekyll-seo-tag
