title: "Magical Musings"
description: "Ramblings of an aspiring Wizard."
tagline: "Ramblings of an aspiring Wizard."
# theme: jekyll-theme-leaf
baseURL: "/magicalmusings.github.io/"

# for a clean URL
permalink: :slug

exclude: 
  - [vendor]
  - .jekyll-cache

incremental: true

markdown: kramdown

kramdown:
  parse_block_html: true

social:
  twitter: anders_magi
  github: magicalmusings

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-include-cache
